### ISSUE TITLE
javascript part

### ISSUE THREAD

**Issue by shtefcs** [kjagiello/foopoker#2]
Hi there,

I am looking for code which I can be use to build poker app in pure javascript/nodejs. Your app have exactly what I need, but it's build in StandardML which is not familiar to me other people.

Is there any part of javascript code can be used from this project into my poker app ?

**Comment by joolify** [comment]
Hi shtefcs!
What is it that you want? Do you want the hand evaluator? We have ported the hand evaluator from "Cactus Kev's Poker Hand Evaluator" which is explained at this site:
http://www.suffecool.net/poker/evaluator.html

Here's a link to an cached suffecool (with working links):
http://web.archive.org/web/20120206063818/http://www.suffecool.net/poker/evaluator.html

Unfortunately the code links at the bottom of the site not working. But you can get them from here:
http://www.filedropper.com/poker_1

Here's an optimization of the code (it's included in the zip above):
http://www.paulsenzee.com/2006/06/some-perfect-hash.html

I hope this helps!

**Comment by shtefcs** [comment]
Hi Joolify,

Tnx for ur links, but it's not what i am looking for. I am looking for open source code ok poker app which I can use to build GUI on it, but in javascript. I found it many, but this one have UI, login, Rooms which is exactly what I was looking for. But the problem its written in StandardML language.

So I was asking is there some part of .js code can be used ?

**Comment by kjagiello** [comment]
Nah, only the frontend uses some JS, but I wouldn't say there is anything valuable there.

**Comment by shtefcs** [comment]
oki, tnx
